name: Continous

on: [push]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Clean install dependencies
        run: npm ci

      - name: Format
        run: npm run prettier:check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
